name: RICM_lib

channels:
    - conda-forge
    - esri

dependencies:
    - python>=3.8
    - pip
    - numpy
    - scipy
    - scikit-image
    - matplotlib-base
    - joblib
    - pystackreg
    - tensorflow-gpu
    - pip:
        - spyder
    
    
